### ISSUE TITLE
проблема Date.parse 

### ISSUE THREAD

**Issue by knasyrov** [yaroslav/russian#58]
2.2.1 :002 > Russian::strftime(Date.new(2015,12,31), "%d %B %Y" )
 => "31 декабря 2015" 
2.2.1 :003 > Date.parse(Russian::strftime(Date.new(2015,12,31), "%d %B %Y" ))
 => Fri, 31 Jul 2015

2.2.1 :007 > Russian::strftime(Date.new(2015,06,30), "%d %B %Y" )
 => "30 июня 2015" 
2.2.1 :008 > Date.parse(Russian::strftime(Date.new(2015,06,30), "%d %B %Y" ))
 => Thu, 30 Jul 2015

**Comment by sagax** [comment]
а какая версия ruby и версия gem 'russian' ?

**Comment by knasyrov** [comment]
ruby 2.2.1 - пробовал и другие
russian 0.6.0

**Comment by sagax** [comment]
собственно я лично это не считаю никакой проблемой. Так как в форматировании нет никакого смысла "%d %B %Y" так как строка будет парситься Date.parse. То есть форматирование это удобство для кого, для Date.parse форматировать вывод совсем не надо. Date.parse понимает разделение между значениями
/   - "2014/12/31"
-   - "2014-12-31"
.   - "2014.12.31"
И работает с такими значениями Date.parse корректно. Считаю что форматировать вывод Russian::strftime в случае когда строка будет отдана парсеру не нужно. Потому ошибки никакой тут не вижу.

**Comment by knasyrov** [comment]
уже разобрался, что проблема не гема - а стандартной библиотеки

26 июля 2015 г., 0:01 пользователь sagax <notifications@github.com> написал:

**Comment by sagax** [comment]
тогда и закрыть этот вопрос можно
